#
# Cookbook:: Cloudera_Automation
# Recipe:: update_host_file
#
# Copyright:: 2018, The Authors, All Rights Reserved.

hostsfile_entry '192.168.1.230' do
  hostname  'default-centos-7.vagrantup.com'
  unique    true
  comment 'This entry is generated by chef! Please do not change it manually!'
end
