driver:
  name: vagrant
  network:
        - ["private_network", {bridge: 'en10: Wi-Fi (AirPort) New', ip: "192.168.2.230"}]
  customize:
    memory: 10240
    cpus: 4

provisioner:
  name: chef_zero
  require_chef_omnibus: true
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  #- name: ubuntu-16.04
  - name: centos-7
  # - name: centos-6.7
  # - name: centos-7.3
  # - name: debian-6.0.10
  #   run_list:
  #   - apt::default
  # - name: ubuntu-12.04
  #   run_list:
  #   - apt::default
  # - name: ubuntu-14.04
  #   run_list:
  #   - apt::default
  # - name: ubuntu-16.04
  #   run_list:
  #   - apt::default
  #
suites:
  - name: default
    run_list:
      - recipe[Cloudera_Automation::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
